### ISSUE TITLE
Chapter about records

### ISSUE THREAD

**Issue by sporto** [gleam-lang/website#17]
When learning Gleam I was quite confused about how to make a Struct / Record

I couldn't find this at a glance in the website. Only after reading the changelog I understood that a record is just a Custom Type with one variant.

Would you include a chapter about `Records` just after `Custom types`?

It will just explain this, give an example and show how to access fields.
I could make a PR if so.

**Comment by lpil** [comment]
Thanks for the feedback. I've a few more questions so I can understand the idea:

What made you search for records?

What would record documentation say that the custom type documentation did not?

Did you type "record" in the search box on the documentation site?

**Comment by sporto** [comment]
Hi @lpil 

> What made you search for records?

I'm familiar with the concept of records or structs from langs like Elm, Rust, Haskell, Purescript, etc

When reading Gleam docs I was expecting to find the keyword `record` or `struct` in a prominent place (the left nav). 

I saw `Custom types` but I dismissed that, because from my experience custom types are ADTs. And ADTs require pattern matching and that is not what I was looking for. I wanted a straightforward record.

What would record documentation say that the custom type documentation did not?

I think the name `Custom types` is misleading, at least for me it was. 
I think the idea of records should be easy to recognize and find in the navigation.

The documentation will mention that records are just custom types in Gleam, it will show how to make one, how to access fields.

Did you type "record" in the search box on the documentation site?

I think I did, but didn't find anything useful. I saw the word record but it wasn't clear to me.

**Comment by lpil** [comment]
Gleann unified the concept of custom types/ADTs and (Elm style) records as our custom types are more powerful, a superset of both.

We won't be splitting them into two separate constructs, but we could later perhaps write done cheat-sheets for people coming from other languages.
