### ISSUE TITLE
Gleam for Python users not up-to-date with features from Python 3.10

### ISSUE THREAD

**Issue by guilherme-puida** [gleam-lang/website#174]
Python 3.10 was still in alpha when the [`case`](https://gleam.run/cheatsheets/gleam-for-python-users/#case) section on the Gleam for Python users cheatsheet was last updated. However, 3.10 was released ~7mo ago, so that section is not completely up-to-date.

Referencing features already in stable versions as not yet released can confuse readers. I'm willing to update the section if needed!

**Comment by lpil** [comment]
Great catch! If you could fix that it would be really useful. Thank you 🙏

**Comment by trag1c** [comment]
Looks like this was fixed by #239 :+1:

**Comment by lpil** [comment]
Thank you
