### ISSUE TITLE
Layout breaks on certain screens

### ISSUE THREAD

**Issue by arothuis** [gleam-lang/website#207]
I noticed this in the [cli reference](https://gleam.run/writing-gleam/command-line-reference/) when I visited on my phone (here emulated in Chrome):

![image](https://user-images.githubusercontent.com/3816591/206292454-8222142e-b7f6-4371-b24f-57acbd688c08.png)

The culprit in this case seems to be the following `<code>` block:
![image](https://user-images.githubusercontent.com/3816591/206293150-91854d4a-66b0-4776-b317-409d8f41f5f2.png)

This behavior is caused by `white-space: nowrap;`. A fix would be to use a block-element like `<pre>` or style the  wrapping differently (e.g. `white-space: normal` or `white-space: pre-line`) on this one.

Additionally, we could consider a block element with `overflow-x: auto`. This presents a scrollable code-block on screens that lack horizontal space.

**Comment by HatGuy68** [comment]
The issue seems to be happening because `<code>` has the CSS property of `white-space: nowrap;`.

**Comment by lpil** [comment]
Thank you @HatGuy68
