### ISSUE TITLE
Command line reference page incomplete; also has apparently inconsistent h2/h3

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [gleam-lang/website#209]
At https://gleam.run/writing-gleam/command-line-reference/, e.g. [publish](https://gleam.run/writing-gleam/command-line-reference/#publish) is `h3`, [deps-list](https://gleam.run/writing-gleam/command-line-reference/#deps-list) is `h2`.

The reference is also missing (maybe not all are relevant):

* `check`
* `clean`
* `help`
* `update`

**Comment by lpil** [comment]
Oops, thank you.

**Comment by HatGuy68** [comment]
Hi @lpil, I would like to work on the documentation for this project. Can you please assign this issue to me?

**Comment by lpil** [comment]
Thank you @HatGuy68 !
