### ISSUE TITLE
✨ emoji has bad contrast on Windows

### ISSUE THREAD

**Issue by mybearworld** [gleam-lang/website#299]
There's probably not a lot y'all can do about this, but the contrast of the sparkles emoji and the pastel pink is pretty poor on Windows 11:
![The sparkles on the pink background, with quite poor contast](https://github.com/gleam-lang/website/assets/130385691/a5415d81-78d7-4eb6-a1a1-0503de408924)

**Comment by lpil** [comment]
Thank you

**Comment by markholmes** [comment]
This was fixed in #308

**Comment by lpil** [comment]
Thanks Mark
