### ISSUE TITLE
How do I run hello_world?

### ISSUE THREAD

**Issue by sporto** [gleam-lang/website#3]
In https://github.com/gleam-lang/website/blob/master/src/getting-started/creating-a-project.md

We create a project that has `hello_world()`
Then there is no  instruction on how to run that.
Doing `rebar3 shell` just throws me into a repl with no indication of what to do.
Would be great if the steps to run `hello_world()` would be there.

Thanks
Sebastian

**Comment by lpil** [comment]
Hi there! Erlang is not as straightforward for running code as other languages. With rebar3 we would most likely either run the shell and call our function using the Erlang syntax (`my_module:hello_world().`), run it using tests (run with `rebar3 eunit`), or by making an escript. I'm unable to share the docs at the moment as I'm about to lose phone signal but you can find them on the rebar3 website.

We may add some additional tooling to Gleam to make this more straightforward, it is unfriendly at the moment.

**Comment by sporto** [comment]
Hi, I understand it is not straightforward. But it would be nice to put some instructions in the getting started e.g. (not sure if this is correct)

```
rebar3 shell
my_fantastic_project:hello_world() .
```

At least in an introduction.

**Comment by lpil** [comment]
Great idea! One to add to the documentation for sure
