### ISSUE TITLE
Website license

### ISSUE THREAD

**Issue by logaan** [gleam-lang/website#300]
I've started writing a [https://learnxinyminutes.com/](https://learnxinyminutes.com/) guide for Gleam. Many of the code examples from the Gleam website would be perfect for adding to the guide (eg: [Ints & Floats](https://gleam.run/book/tour/ints-and-floats.html)). I've had a look through this website and I see "© 2024 Louis Pilfold" and no other licence file or marker.

If you would be ok with folks copying parts of the website content might it be possible to ad a LICENCE file? Perhaps Apache License 2.0 [to match Gleam itself](https://github.com/gleam-lang/gleam/blob/main/LICENCE).

If you'd prefer to keep the website contents in general under Copyright then @lpil could I please get permission to make use of the code examples for the purposes of creating the [https://learnxinyminutes.com/](https://learnxinyminutes.com/) guide for Gleam?

Thanks

**Comment by lpil** [comment]
Ah yes! This should be apache licenced. I'll add that now.
