### ISSUE TITLE
Remove a phrase in the frontpage.

### ISSUE THREAD

**Issue by ameknite** [gleam-lang/website#320]
Hi, I just found this programming language and I'm really liking it

While reading the website, I found this phrase: `No nazi bullsh*t` in the front page, and I think it should be removed it.
As a newcomer It doesn't look good having cursing and the word `nazi` in the front page.
I think it goes against the meaning of being `Friendly 💜` and because web indexing, the website could be ended related to that. I think it is better just stay away from that word

**Comment by lpil** [comment]
Hello! Thanks for your input! The wording on the homepage is carefully considered and is not changing at the present time.
