### ISSUE TITLE
Maybe the click effect on the little star icon on the home page is a bit too sudden 

### ISSUE THREAD

**Issue by tulilirockz** [gleam-lang/website#325]
It probably is not a great idea to have an element when, when clicked, brightens the screen instantly from one color, to another. Maybe replacing that effect with something less intrusive like little stars falling off of the big star, or just a little glow, would be best! 

Great job with this language! Came from Theo's video about this.

**Comment by lpil** [comment]
We're keeping the rainbow, but if you want to add some transition animation that would be really cool!
