### ISSUE TITLE
Automate regenerating of the website?

### ISSUE THREAD

**Issue by michallepicki** [gleam-lang/website#33]
I am not sure if it's an actual hassle, so feel free to close this.

I saw that after merging PRs with small tweaks to the documents src, @lpil has to push a follow-up commit with regenerated website changes.

Maybe GitHub Actions could be used to automatically re-generate the website when there were changes? A common pattern I saw is: the main repo branch holds just the page source, and a gh-pages branch holds just the output.

**Comment by lpil** [comment]
That would be a great addition for sure! I don't mind manually doing this but automation would be better, I've just not had the time,

**Comment by lpil** [comment]
I'm moving over to Jekyll so GitHub will handle this for us soon :)

**Comment by michallepicki** [comment]
@lpil If you want, running `mdbook` could also be automated. I just submitted a PR to Caramel to do this through Github Actions and force pushing to a separate gh-pages branch: https://github.com/AbstractMachinesLab/caramel/pull/48

**Comment by lpil** [comment]
Honestly I'd rather just get the tour out of mdbook and into jekyll. It's laziness on my part that keeps it in there at the moment.
