### ISSUE TITLE
Explain what gets automatically imported as part of Prelude

### ISSUE THREAD

**Issue by michallepicki** [gleam-lang/website#34]
I found out that `BitString` just works without importing so I was looking for resources as to what types or functions should work out of the box and I couldn't find any documentation. I only found the [source code](https://github.com/gleam-lang/gleam/blob/844b06aaa2240f0735815d91fa9068b1d84b58fe/src/typ/prelude.rs)

**Comment by lpil** [comment]
Great shout, thank you!

**Comment by michallepicki** [comment]
Closing in favor of https://github.com/gleam-lang/gleam/issues/1022

**Comment by lpil** [comment]
Ah nice one, thank you
