### ISSUE TITLE
Missing GitHub link on the website

### ISSUE THREAD

**Issue by babakfp** [gleam-lang/website#353]
Add a link to this GitHub org in the footer of the website.

**Comment by lpil** [comment]
There's already a link to the github in the footer and another in the header.

**Comment by babakfp** [comment]
Ah, correct, it's "Code". I think it's better to change it to "GitHub". Maybe at least change only the one in the footer? Or, add the GitHub icon like how it's done here: https://gitbutler.com

**Comment by lpil** [comment]
Could be cool. Would you like to make a mockup of the design? :)

**Comment by babakfp** [comment]
Sure 😸. What do you mean by mockup? Do you mean a PR/Demo?

**Comment by lpil** [comment]
Just some way of seeing what the new design might look like so we can decide which and any design to go with.

**Comment by babakfp** [comment]
Dude, never mind. Ruby sucks. I can't deal with it. Sorry 🌸.
