### ISSUE TITLE
Fly.io logo looks bad on dark background

### ISSUE THREAD

**Issue by babakfp** [gleam-lang/website#354]
![image](https://github.com/gleam-lang/website/assets/44144724/52cc7f64-5546-4bd6-8132-c9523470faa2)

https://gleam.run/news/v0.25-introducing-use-expressions/

I'm not sure if this is that important or not. I randomly clicked on a link and saw this. It doesn't look good 🤷‍♂️

**Comment by lpil** [comment]
Ah yes. Let's use one of the inverted logos here: https://fly.io/docs/about/brand/
