### ISSUE TITLE
Add installation flow to the homepage

### ISSUE THREAD

**Issue by ControlCplusControlV** [gleam-lang/website#358]
Sorry I am may be kind of stupid, but for the life of me I can't see how to install gleam from the main website, showing a `rustup` or similar command I can run to get started with Gleam would go a long way for user flow and conversion

**Comment by lpil** [comment]
I agree! Unfortunately no such tool exists. When the community has made one we can include it on the homepage. Thank you.

**Comment by ControlCplusControlV** [comment]
Not even a `brew install gleam` on MacOs or `choc install gleam` on Windows suggested there? Or `Download from Github` and link to the latest release?

**Comment by lpil** [comment]
Those do exist but we don't have a reliable approach for all major platforms yet.
