### ISSUE TITLE
Please specify preferred Lucy icon source

### ISSUE THREAD

**Issue by Rudxain** [gleam-lang/website#359]
This was a question I had, but I believe it would be better if it was answered directly on the website, instead of a GH-Discussion or a Discord guild.

Which of the following domains should be referenced when embedding any Lucy-related images (or anything related to branding)?:
- [Repo's Raw GH user-content](https://raw.githubusercontent.com/gleam-lang/website/main/images/lucy/lucy.svg)
- [GH Pages](https://gleam.run/images/lucy/lucy.svg)

GHP is shorter and cleaner, but is it always the best domain? Are there any legal issues with using either domain?

One of the reasons "raw" can be useful, is because the branch can be replaced by a commit, effectively making it a permalink, without the need for tools such as The Wayback Machine.

My specific use-case is to [use Lucy as an emoji](https://github.com/Rudxain/custom-emoji-inliner) in Markdown files

**Comment by lpil** [comment]
Hello! Best to host it yourself as there's no guarantee of those URLs remaining.

Also be sure to rotate the image 10 degrees anticlockwise, as advised on the branding page. https://gleam.run/branding/
