### ISSUE TITLE
Running The Project page doesn't fit on mobile

### ISSUE THREAD

**Issue by michallepicki** [gleam-lang/website#36]
The links at the bottom of the page cause it to have bigger width. Screenshot: 
![Screenshot_20200910-075325_Samsung Internet](https://user-images.githubusercontent.com/4972756/92687029-10481180-f33b-11ea-9587-85aebbbc1969.jpg)

Encountered on Samsung Internet on Android

[Link to that page](https://gleam.run/writing-gleam/running-the-project/)

**Comment by lpil** [comment]
Thank you

**Comment by lpil** [comment]
I wasn't able to reproduce the problem on my devices but I've pushed something I think may help. Could you have another look in a few minutes please? Thanks

**Comment by michallepicki** [comment]
Looks good now!

**Comment by lpil** [comment]
Thanks!
