### ISSUE TITLE
Invalid Discord invite link under The Gleam Community

### ISSUE THREAD

**Issue by ilaitinen** [gleam-lang/website#370]
Following [a link to the Discord chat](https://discord.gg/Fm8Pwmy) on [Community page](https://gleam.run/community/) results in an "Invalid Invite" error message.

**Comment by lpil** [comment]
Hello! I've tested this multiple times and have been unable to reproduce. Could you share a screenshot?

**Comment by ilaitinen** [comment]
When following the link I saw:

<img width="1679" alt="Screenshot 2024-04-16 at 0 13 46" src="https://github.com/gleam-lang/website/assets/1655649/251bd97e-84aa-4753-8a5d-103919709b4e">

I was not logged into Discord.

On the other hand, in Incognito mode it looked like it should:

<img width="1680" alt="Screenshot 2024-04-16 at 0 16 53" src="https://github.com/gleam-lang/website/assets/1655649/0c007259-cf37-4481-aba8-3999b8704375">

This observation lead me to try deleting Discord.com's local and session storage using the browser's developer tools, and it worked!

Looks like this was probably a bug on Discord's part.

**Comment by lpil** [comment]
Thank you
