### ISSUE TITLE
Nix installation instructions are out of date for version 24.05 (Uakari)

### ISSUE THREAD

**Issue by bonsairobo** [gleam-lang/website#389]
I believe the instruction `nix profile install gleam` needs to change to `nix profile install nixpkgs#gleam`.

This is necessary while there is no entry in the flakes repo for gleam.

**Comment by bonsairobo** [comment]
Followup: it seems like there is also a prerequisite of installing the Erlang toolchain, but instructions are not provided for installing on NixOS. I have additionally run `nix profile install nixpkgs#erlang` to fix this.

**Comment by lpil** [comment]
Thank you
