### ISSUE TITLE
Too hard to find install guide.

### ISSUE THREAD

**Issue by zvodd** [gleam-lang/website#399]
Granted my brain is pretty smooth, but my raw take is:
It took me multiple minutes to find the install guide.

I would have really appreciated finding a "download" or "get gleam" or "install" link on the menu bar or front page.
That is fairly  standard for many "product" websites and its a jarring experience to have to dig for it.

Could be that other potential new user might lose interest before getting there.
> That seems like a bad situation in terms of growing user base.

**Comment by lpil** [comment]
Please see prior discussion. Thanks
