### ISSUE TITLE
Erlang apt PPA does not work

### ISSUE THREAD

**Issue by BatmanAoD** [gleam-lang/website#411]
This issue describes a problem I ran into while attempting to install Erlang on Ubuntu (on WSL): https://github.com/elixir-lang/elixir-lang.github.com/issues/1575

Specifically, Erlang's PPA (their hosted source for Debian/Ubuntu packages) appears to be broken, at least for Ubuntu 22.04 (Jammy).

Since Gleam's installation instructions recommend using the PPA, it might be preferable to recommend a different approach. Unfortunately, I'm not sure what the most straightforward/correct path would actually be, though I did add a comment on the Elixir issue thread describing my installation approach (downloading the `.deb` file directly and installing with `apt`).

**Comment by Janiczek** [comment]
Erlang Solutions has instructions for installing Erlang on Ubuntu different from the "Installing Gleam" doc:

https://www.erlang-solutions.com/downloads/#

They're roughly:

```
# Add to /etc/apt/sources.list
deb http://binaries2.erlang-solutions.com/ubuntu/ jammy-esl-erlang-25 contrib
# Possible other lines depending on your `lsb_release -c`
# deb http://binaries2.erlang-solutions.com/debian/ bullseye-elixir-1.15 contrib
# deb http://binaries2.erlang-solutions.com/ubuntu/ bionic-mongooseim-6 contrib

# Add Erlang Solutions repo keys:
wget https://binaries2.erlang-solutions.com/GPG-KEY-pmanager.asc
sudo apt-key add GPG-KEY-pmanager.asc

# Update apt and install esl-erlang
sudo apt update
sudo apt install esl-erlang
```

**Comment by lpil** [comment]
Thank you
