### ISSUE TITLE
The "Editor plugins" link on the "Getting Started" page is broken

### ISSUE THREAD

**Issue by michaeljones** [gleam-lang/website#42]
As the title, there is an "Editor plugins" link in the table of contents but it doesn't link anywhere. I would offer a fix but I'm not sure if the content exists somewhere to be linked to or if it is best removed for the moment.

**Comment by lpil** [comment]
Looks like I forgot to copy this section to the new getting started page

https://github.com/gleam-lang/website/commit/b840af3cfe0ebbc07da8666115e3feedac08a239#diff-884980f7a8d9ae30a86b80ae2427e7e05d6268d4daa7884b9fec9aae330410a7

**Comment by michaeljones** [comment]
Would you like that as a separate page or just down the bottom of this one?

**Comment by lpil** [comment]
Another section at the bottom of this page please 💜

**Comment by michaeljones** [comment]
You should give a conference talk on encouraging community participation and contributions :) I really respect your approach.

**Comment by lpil** [comment]
Thank you! That's really kind of you to say.

I'm about to start a new job that will involve some amount of open source community work, and I like the conference talk idea. I've some thoughts but if possible it would be really cool to get an idea of what things you think work well, to help me validate my ideas and learn some tricks of yours :)
