### ISSUE TITLE
Suggestion: add an "Install" link to header menu

### ISSUE THREAD

**Issue by riseremi** [gleam-lang/website#434]
Hello!

I am a first-time user. I tried to find an "Install" link in the header menu but were not able to.
Then I googled it and it came up as the first result.

I suggest adding it maybe like this to help someone in the future.

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/894adfca-d38a-4a4b-a56f-284c794b9d8f">

Thank you!

**Comment by lpil** [comment]
Please see previous discussion for details, but in short the install page is not good enough yet to be part of the main funnel so it will continue to come after the tour until it is fixed.
