### ISSUE TITLE
Install option in the main header 

### ISSUE THREAD

**Issue by itsjzt** [gleam-lang/website#442]
Currently there is no easy path to find the instruction to install the language. It is very common action so it deserves a place in the main header.

My idea is we can replace the link of `Code` with the link of `Install` and if need we can use a github icon to represent the link for code code.

![Add a little bit of body text](https://github.com/user-attachments/assets/80e5c0ab-bc2c-4e66-bb00-65d1bc3f4cd9)

Let me know if it works.

**Comment by lpil** [comment]
Please see prior discussion.
