### ISSUE TITLE
[bug] typo in "Gleam for Python Users" explanation of labelled arguments

### ISSUE THREAD

**Issue by gvwilson** [gleam-lang/website#445]
The section on labelled arguments in "Gleam for Python Users" presents this fragment of Gleam:

```
pub fn replace(inside string, each pattern, with replacement) {
  go(string, pattern, replacement)
}
```

Should the first argument to `go(...)` be `inside` rather than `string`?

**Comment by lpil** [comment]
No, `inside` is the label, not the variable.
