### ISSUE TITLE
Fix link in convenient-code-actions news entry

### ISSUE THREAD

**Issue by escherize** [gleam-lang/website#451]
in https://github.com/gleam-lang/website/blob/main/_posts/2024-09-19-convenient-code-actions.md?plain=1#L740

```
- [Lukas Meihsner](https://github.com/lukasmei
```

This link is broken, and if it matches `Lukas Meihsner`'s github link in the other new entry, it should read:

```
- [Lukas Meihsner](https://github.com/lukasmeihsner)
```

**Comment by lpil** [comment]
Thank you
