### ISSUE TITLE
Compile-time error instead of runtime error

### ISSUE THREAD

**Issue by David-Klemenc** [gleam-lang/website#47]
[Case expressions - Destructuring](https://github.com/gleam-lang/website/blob/main/book/tour/case-expressions.html) in the example:

---

<p>Pattern matching also works in <code>let</code> bindings, though patterns that do not
match all instances of that type may result in a runtime error.</p>
<pre><code class="language-rust noplaypen">let [a] = [1]    // a is 1
let [b] = [1, 2] // Runtime error! The pattern has 1 element but the value has 2
</code></pre>

---

I think the comment should be `// Compile-time error! The pattern has 1 element but the value has 2`

**Comment by lpil** [comment]
It's a runtime error I'm afraid. Currently Gleam doesn't have exhaustiveness checking. https://github.com/gleam-lang/gleam/issues/34

**Comment by David-Klemenc** [comment]
Ahh thank you for the response - did not realise that!

**Comment by lpil** [comment]
No worries! Hopefully it'll be compile time soon.
