### ISSUE TITLE
The entire 3. Writing Gleam section in the book is blank

### ISSUE THREAD

**Issue by adituv** [gleam-lang/website#50]
As in the issue name, the whole 3rd section in the book is blank.  However, the details are present on the documentation site itself.

For example:
* [Docs: Creating a Project](https://gleam.run/writing-gleam/creating-a-project/)
* [Book: Creating a Project](https://gleam.run/book/writing-gleam/creating-a-project.html)

**Comment by lpil** [comment]
Oops, thank you.

**Comment by michallepicki** [comment]
Same with the first section
