### ISSUE TITLE
escape characters are shown on Elixir cheat sheet

### ISSUE THREAD

**Issue by simonmcconnell** [gleam-lang/website#57]
On the [gleam for elixir users page](https://gleam.run/cheatsheets/gleam-for-elixir-users/) under **Operators**, the escape characters are shown, so `||` displays as `\|\|`.  On the Erlang cheat sheet the issue isn't present, however the | character looks huge, unlike the rest of them.

Elixir:
![image](https://user-images.githubusercontent.com/22566656/98452753-3573c780-21a6-11eb-8cd3-beff57deca14.png)

Erlang:
![image](https://user-images.githubusercontent.com/22566656/98452764-47ee0100-21a6-11eb-9e46-94c30d91e5be.png)

**Comment by lpil** [comment]
Thank you
