### ISSUE TITLE
Document blocks 

### ISSUE THREAD

**Issue by edman** [gleam-lang/website#71]
I went over the gleam book / language tour, and started a little project.

This issue bit me for some good 30 minutes.

https://github.com/gleam-lang/gleam/issues/155

Can we improve the documentation? Maybe a mention to this on https://gleam.run/book/tour/ints-and-floats.html?

Helpful error messages would be great, but even a helpful note on the language tour would have saved me here.

**Comment by lpil** [comment]
While it would be difficult to document all syntax that Gleam does not support it would be very useful to have a section on blocks. Let's do this for sure
