### ISSUE TITLE
RSS feed for news

### ISSUE THREAD

**Issue by gampleman** [gleam-lang/website#78]
👋 Hello!

I've been interested in Gleam for a while and would like to keep myself in the loop around new releases. My normal way to do that would be by subsribing to the RSS feed for news.

However, there is no RSS feed there 😢  Would you be happy to have one? I think there is a plugin for GitHub pages that generates one... I'd be happy to PR if this seems like a good idea.

**Comment by lpil** [comment]
That would be a great addition. It seems like this is a plugin we could use.

https://github.com/jekyll/jekyll-feed

What feed reader do you use? I was thinking about trying RSS myself.

**Comment by gampleman** [comment]
I use [NetNewsWire](https://ranchero.com/netnewswire/) which is great (Apple platforms only though). For me the trick with RSS is mostly to subscribe to things that update infrequently and check high volume stuff manually. That way your RSS feed reader feels like a place to discover gems you would have likely missed.

Anyway, I'll try to cook up a PR.
