### ISSUE TITLE
Footer rendering issue on mobile

### ISSUE THREAD

**Issue by michallepicki** [gleam-lang/website#87]
![Screenshot_20210211-192309_Firefox](https://user-images.githubusercontent.com/4972756/107680991-d17a0700-6c9e-11eb-9102-a5f8812a92d3.jpg)
Page is https://gleam.run/ , browser is Firefox for Android. There are just too many sponsors! 😄

**Comment by lpil** [comment]
> There are just too many sponsors! 😄

😂 

Thanks for the report!
